// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: file_chunks_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileChunksService_CreateFileChunks_FullMethodName           = "/FileChunksService/CreateFileChunks"
	FileChunksService_GetSortedFileChunksContent_FullMethodName = "/FileChunksService/GetSortedFileChunksContent"
)

// FileChunksServiceClient is the client API for FileChunksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileChunksServiceClient interface {
	CreateFileChunks(ctx context.Context, in *CreateFileChunksRequest, opts ...grpc.CallOption) (*CreateFileChunksResponse, error)
	GetSortedFileChunksContent(ctx context.Context, in *GetSortedFileChunksContentRequest, opts ...grpc.CallOption) (*GetSortedFileChunksContentResponse, error)
}

type fileChunksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileChunksServiceClient(cc grpc.ClientConnInterface) FileChunksServiceClient {
	return &fileChunksServiceClient{cc}
}

func (c *fileChunksServiceClient) CreateFileChunks(ctx context.Context, in *CreateFileChunksRequest, opts ...grpc.CallOption) (*CreateFileChunksResponse, error) {
	out := new(CreateFileChunksResponse)
	err := c.cc.Invoke(ctx, FileChunksService_CreateFileChunks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileChunksServiceClient) GetSortedFileChunksContent(ctx context.Context, in *GetSortedFileChunksContentRequest, opts ...grpc.CallOption) (*GetSortedFileChunksContentResponse, error) {
	out := new(GetSortedFileChunksContentResponse)
	err := c.cc.Invoke(ctx, FileChunksService_GetSortedFileChunksContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileChunksServiceServer is the server API for FileChunksService service.
// All implementations must embed UnimplementedFileChunksServiceServer
// for forward compatibility
type FileChunksServiceServer interface {
	CreateFileChunks(context.Context, *CreateFileChunksRequest) (*CreateFileChunksResponse, error)
	GetSortedFileChunksContent(context.Context, *GetSortedFileChunksContentRequest) (*GetSortedFileChunksContentResponse, error)
	mustEmbedUnimplementedFileChunksServiceServer()
}

// UnimplementedFileChunksServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileChunksServiceServer struct {
}

func (UnimplementedFileChunksServiceServer) CreateFileChunks(context.Context, *CreateFileChunksRequest) (*CreateFileChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileChunks not implemented")
}
func (UnimplementedFileChunksServiceServer) GetSortedFileChunksContent(context.Context, *GetSortedFileChunksContentRequest) (*GetSortedFileChunksContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSortedFileChunksContent not implemented")
}
func (UnimplementedFileChunksServiceServer) mustEmbedUnimplementedFileChunksServiceServer() {}

// UnsafeFileChunksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileChunksServiceServer will
// result in compilation errors.
type UnsafeFileChunksServiceServer interface {
	mustEmbedUnimplementedFileChunksServiceServer()
}

func RegisterFileChunksServiceServer(s grpc.ServiceRegistrar, srv FileChunksServiceServer) {
	s.RegisterService(&FileChunksService_ServiceDesc, srv)
}

func _FileChunksService_CreateFileChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileChunksServiceServer).CreateFileChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileChunksService_CreateFileChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileChunksServiceServer).CreateFileChunks(ctx, req.(*CreateFileChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileChunksService_GetSortedFileChunksContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSortedFileChunksContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileChunksServiceServer).GetSortedFileChunksContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileChunksService_GetSortedFileChunksContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileChunksServiceServer).GetSortedFileChunksContent(ctx, req.(*GetSortedFileChunksContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileChunksService_ServiceDesc is the grpc.ServiceDesc for FileChunksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileChunksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileChunksService",
	HandlerType: (*FileChunksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileChunks",
			Handler:    _FileChunksService_CreateFileChunks_Handler,
		},
		{
			MethodName: "GetSortedFileChunksContent",
			Handler:    _FileChunksService_GetSortedFileChunksContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_chunks_service.proto",
}
