// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: summarizer.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SummarizerService_CreateFileComponentSummaries_FullMethodName = "/SummarizerService/CreateFileComponentSummaries"
)

// SummarizerServiceClient is the client API for SummarizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummarizerServiceClient interface {
	CreateFileComponentSummaries(ctx context.Context, in *CreateFileComponentSummariesRequest, opts ...grpc.CallOption) (*FileComponentSummaries, error)
}

type summarizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSummarizerServiceClient(cc grpc.ClientConnInterface) SummarizerServiceClient {
	return &summarizerServiceClient{cc}
}

func (c *summarizerServiceClient) CreateFileComponentSummaries(ctx context.Context, in *CreateFileComponentSummariesRequest, opts ...grpc.CallOption) (*FileComponentSummaries, error) {
	out := new(FileComponentSummaries)
	err := c.cc.Invoke(ctx, SummarizerService_CreateFileComponentSummaries_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummarizerServiceServer is the server API for SummarizerService service.
// All implementations must embed UnimplementedSummarizerServiceServer
// for forward compatibility
type SummarizerServiceServer interface {
	CreateFileComponentSummaries(context.Context, *CreateFileComponentSummariesRequest) (*FileComponentSummaries, error)
	mustEmbedUnimplementedSummarizerServiceServer()
}

// UnimplementedSummarizerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSummarizerServiceServer struct {
}

func (UnimplementedSummarizerServiceServer) CreateFileComponentSummaries(context.Context, *CreateFileComponentSummariesRequest) (*FileComponentSummaries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFileComponentSummaries not implemented")
}
func (UnimplementedSummarizerServiceServer) mustEmbedUnimplementedSummarizerServiceServer() {}

// UnsafeSummarizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummarizerServiceServer will
// result in compilation errors.
type UnsafeSummarizerServiceServer interface {
	mustEmbedUnimplementedSummarizerServiceServer()
}

func RegisterSummarizerServiceServer(s grpc.ServiceRegistrar, srv SummarizerServiceServer) {
	s.RegisterService(&SummarizerService_ServiceDesc, srv)
}

func _SummarizerService_CreateFileComponentSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileComponentSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizerServiceServer).CreateFileComponentSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SummarizerService_CreateFileComponentSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizerServiceServer).CreateFileComponentSummaries(ctx, req.(*CreateFileComponentSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SummarizerService_ServiceDesc is the grpc.ServiceDesc for SummarizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SummarizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SummarizerService",
	HandlerType: (*SummarizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileComponentSummaries",
			Handler:    _SummarizerService_CreateFileComponentSummaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summarizer.proto",
}
