// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: file_components_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileComponentsService_BatchExtractFileComponents_FullMethodName = "/FileComponentsService/BatchExtractFileComponents"
	FileComponentsService_SaveFileComponents_FullMethodName         = "/FileComponentsService/SaveFileComponents"
	FileComponentsService_GetSavedFileComponents_FullMethodName     = "/FileComponentsService/GetSavedFileComponents"
)

// FileComponentsServiceClient is the client API for FileComponentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileComponentsServiceClient interface {
	BatchExtractFileComponents(ctx context.Context, in *BatchExtractFileComponentsRequest, opts ...grpc.CallOption) (*FileComponents, error)
	SaveFileComponents(ctx context.Context, in *FileComponents, opts ...grpc.CallOption) (*SavedFileComponentIds, error)
	GetSavedFileComponents(ctx context.Context, in *SavedFileComponentIds, opts ...grpc.CallOption) (*SavedFileComponents, error)
}

type fileComponentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileComponentsServiceClient(cc grpc.ClientConnInterface) FileComponentsServiceClient {
	return &fileComponentsServiceClient{cc}
}

func (c *fileComponentsServiceClient) BatchExtractFileComponents(ctx context.Context, in *BatchExtractFileComponentsRequest, opts ...grpc.CallOption) (*FileComponents, error) {
	out := new(FileComponents)
	err := c.cc.Invoke(ctx, FileComponentsService_BatchExtractFileComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileComponentsServiceClient) SaveFileComponents(ctx context.Context, in *FileComponents, opts ...grpc.CallOption) (*SavedFileComponentIds, error) {
	out := new(SavedFileComponentIds)
	err := c.cc.Invoke(ctx, FileComponentsService_SaveFileComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileComponentsServiceClient) GetSavedFileComponents(ctx context.Context, in *SavedFileComponentIds, opts ...grpc.CallOption) (*SavedFileComponents, error) {
	out := new(SavedFileComponents)
	err := c.cc.Invoke(ctx, FileComponentsService_GetSavedFileComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileComponentsServiceServer is the server API for FileComponentsService service.
// All implementations must embed UnimplementedFileComponentsServiceServer
// for forward compatibility
type FileComponentsServiceServer interface {
	BatchExtractFileComponents(context.Context, *BatchExtractFileComponentsRequest) (*FileComponents, error)
	SaveFileComponents(context.Context, *FileComponents) (*SavedFileComponentIds, error)
	GetSavedFileComponents(context.Context, *SavedFileComponentIds) (*SavedFileComponents, error)
	mustEmbedUnimplementedFileComponentsServiceServer()
}

// UnimplementedFileComponentsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileComponentsServiceServer struct {
}

func (UnimplementedFileComponentsServiceServer) BatchExtractFileComponents(context.Context, *BatchExtractFileComponentsRequest) (*FileComponents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchExtractFileComponents not implemented")
}
func (UnimplementedFileComponentsServiceServer) SaveFileComponents(context.Context, *FileComponents) (*SavedFileComponentIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFileComponents not implemented")
}
func (UnimplementedFileComponentsServiceServer) GetSavedFileComponents(context.Context, *SavedFileComponentIds) (*SavedFileComponents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSavedFileComponents not implemented")
}
func (UnimplementedFileComponentsServiceServer) mustEmbedUnimplementedFileComponentsServiceServer() {}

// UnsafeFileComponentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileComponentsServiceServer will
// result in compilation errors.
type UnsafeFileComponentsServiceServer interface {
	mustEmbedUnimplementedFileComponentsServiceServer()
}

func RegisterFileComponentsServiceServer(s grpc.ServiceRegistrar, srv FileComponentsServiceServer) {
	s.RegisterService(&FileComponentsService_ServiceDesc, srv)
}

func _FileComponentsService_BatchExtractFileComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchExtractFileComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileComponentsServiceServer).BatchExtractFileComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileComponentsService_BatchExtractFileComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileComponentsServiceServer).BatchExtractFileComponents(ctx, req.(*BatchExtractFileComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileComponentsService_SaveFileComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileComponents)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileComponentsServiceServer).SaveFileComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileComponentsService_SaveFileComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileComponentsServiceServer).SaveFileComponents(ctx, req.(*FileComponents))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileComponentsService_GetSavedFileComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavedFileComponentIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileComponentsServiceServer).GetSavedFileComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileComponentsService_GetSavedFileComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileComponentsServiceServer).GetSavedFileComponents(ctx, req.(*SavedFileComponentIds))
	}
	return interceptor(ctx, in, info, handler)
}

// FileComponentsService_ServiceDesc is the grpc.ServiceDesc for FileComponentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileComponentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileComponentsService",
	HandlerType: (*FileComponentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchExtractFileComponents",
			Handler:    _FileComponentsService_BatchExtractFileComponents_Handler,
		},
		{
			MethodName: "SaveFileComponents",
			Handler:    _FileComponentsService_SaveFileComponents_Handler,
		},
		{
			MethodName: "GetSavedFileComponents",
			Handler:    _FileComponentsService_GetSavedFileComponents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_components_service.proto",
}
